### ISSUE TITLE
Crash in thinkpad-dock when sound:unmute ist set

### ISSUE THREAD

**Issue by Aruee** [martin-ueding/thinkpad-scripts#105]
Hi.

thinkpad-dock crashes for me when I do not set [sound] unmute = false in the config file.

This is the output I get:

> thinkpad-dock
> /usr/lib/python3/dist-packages/pkg_resources/__init__.py:1224: UserWarning: /home/xxxx/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
>   warnings.warn(msg, UserWarning)
> Erhalten der Sink-Informationen fehlgeschlagen: Entität nicht vorhanden
> Traceback (most recent call last):
>   File "/usr/local/bin/thinkpad-dock", line 9, in <module>
>     load_entry_point('thinkpad-scripts==4.4.0', 'console_scripts', 'thinkpad-dock')()
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/dock.py", line 220, in main
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/dock.py", line 116, in dock
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/sound.py", line 29, in unmute
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/__init__.py", line 134, in wrapper
>   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['pactl', 'set-sink-volume', '0', '100%']' returned non-zero exit status 1

**Comment by martin-ueding** [comment]
I think this is what I wanted do document when I started #99. The error did not occur on my machine any more, so I forgot about that. Sorry.

This issue is caused by Pulse Audio not finding a sink. You can see it in your stacktrace:

`Erhalten der Sink-Informationen fehlgeschlagen: Entität nicht vorhanden`

So the problem we have is that we unconditionally do something to sink `0`. I think if we just look at the available sinks first before changing anything, this should work.

I have exams coming up. Can you wait until August?

**Comment by Aruee** [comment]
It's totally not urgent. As I said, simply not changing the audio does it for me.

Still, I hopefully fixed it and created a pull request. Maybe this helps. Good look with your exams!
