### ISSUE TITLE
Enable auto-screen rotation using HDAPS accelerometer

### ISSUE THREAD

**Issue by sniffer** [martin-ueding/thinkpad-scripts#113]
Hi,

a nice addition to this script-set might be incorporating the HDAPS (Hard Drive Active Protection System) accelerometer sensor to automatically rotate the screen. From my understanding HDAPS its available on most IBM/Lenovo laptops. Especially X2X0T models and new tablets/convertibles can benefit from this.

You can see this in action here: https://www.youtube.com/watch?v=VOQds5DfC60
Source code here: http://www.helsinki.fi/~rantalai/lenovo_rotate.py

I've adapted the script above to use `thinkpad-rotate <direction>` os binary entry point and removed the synaptics touchpad orientation change call. Everything works as expected:
- screen is rotated when I rotate the laptop,
- touchpad, touchpad buttons and trackpoint are disabled,
- touchscreen works as expected.

My idea here would be to create:
- `thinkpad-autorotated` small daemon script entry point,
- incorporate the logic from the script above in pure python (link it nicely with the rest of the code istead doing os popen calls),
- when no `/sys/devices/platform/hdaps/position` sysfs info is available exit gracefully with appropriate message and exit code,
- add an config option to disable auto screen rotation (optional - if run as a service we can just disable the service),
- add SysV/Systemd unit service files for starting/stoping/monitoring the daemon,
- if `thinkpad-autorotated` service is enabled (and optionally running) we should probably disable screen rotation hardware button(s) since its actions would be immediately overridden,
- accelerometer sensor data will not allow to rotate "invert".

An alternative to the `thinkpad-autorotated` would be to handle an acpi event of accelerometer data change if it is available (I have not researched).

**Comment by martin-ueding** [comment]
The HDAPS automatic rotation was already suggested in #69. At the time I said that I do not want to spend time implementing this as I would not use this myself.

Now you have linked to working code which would make this much simpler. We could just integrate that code into our project. There is a slight catch, though: The code is GPL 3 and we are currently on GPL 2+. If we incorporate that snippet we would have to switch our project to GPL 3 as well as the GPL 3 is not “backwards compatible” in this sense.

I would change a lot of things in the code, for instance compiling the regular expression before using it. Or use more verbose variable names. So one would have to decide how unique that snippet is and how much we take from that. In either case I think the most honest approach would be to either live with the change to GPL 3 or ask the author if GPL 2+ would also be acceptable to him.

The general idea of having an optional daemon sounds good, having it couple to ACPI would be even better as that would not require another program running all the time.

- I would perhaps do this feature as opt-in such that existing users are not confronted with a new feature they would have to disable. The downside of this is that they would not learn about it. I myself do not really read the changelogs of anything. Fedora usually ships with disabled systemd units and you have to enable them after the installation if you want them. On Debian this is the other way around, usually the services are enabled right after installation.

- Having the accelerometer allow invert could be useful in some cases, I don't know. I'd suggest to put in another configuration option. Having a huge config is not cool in itself but I do not see the harm in adding another option for that. As long as the defaults are sane nobody should complain.

- Disabling the hardware keys does not seem too sensible. What we perhaps should disable then is the ACPI event when the screen is switched? I guess one could add configuration options for that as well later on.

If you want to implement that yourself that would be fine. I have exams coming up in around four weeks and I do not think I would use that feature. So I could also do it, but it would be a lower priority. Unless of course I decide to procrastinate by implementing this feature :wink:.

**Comment by sniffer** [comment]
I've decided to put some time into this. I've forked your project, try to implement this and issue a pull request afterwards. We can discuss on all the points you mentioned after including licensing change if it comes to that.

Can you please commit in the ``debian`` directory you use to create Debian packages? This will become useful for everyone.

I've also stumbled upon a more robust solution written in Bash that resembles couple of already discussed points/ideas: http://www.thinkwiki.org/wiki/How_to_rotate_X41t_screen_with_gravity_sensor%28hdaps%29

**Comment by martin-ueding** [comment]
Sounds good! Thanks for your interest in Jim's and my project!

The `debian` folder is now here: https://github.com/martin-ueding/thinkpad-scripts-debian

**Comment by sniffer** [comment]
Hi Martin,

I've pushed a working version of what I had in mind. Take a look into my forked repo. Comments welcome. 

This version is working well on my x220t. You might need to adjust calibration/resolution settings on your laptop to make sure its working correctly. To find both settings you will need to probe:

``watch -n "0,5" -d cat /sys/devices/platform/hdaps/position``

while rotating the laptop into extreme/border positions. I've put some documentation onto the Hdaps class for some more insight.

Also I've integrated the debian dir into this repo for everyones sake.

**Comment by martin-ueding** [comment]
I'll take a look at that in a while, I should be doing my particle physics homework and just wanted to give you a quick response. :smile:

# Debian packaging

The `debian` directory should not be integrated into the upstream project. This should only be done for so called “Debian native” programs like `debuild` and the like. The problem with a `debian` directory in the upstream source is that a packager for Debian cannot just change things without coming back to us. Debian is supposed to be downstream of us and not tightly entangled.

Also they like to be able to do non-maintainer uploads and this would break that too. So really the version control of the `debian` folder should be what is uploaded to the official Debian repositories. Since this package is not part of the official Debian distribution, it does not hurt yet.

I do see the point in collecting all the packaging information for thinkpad-scripts. I would suggest that we do so in separate git repositories in order to let the distributors do their job without us interfering. If the `debian` folder was not in the root of our source but somewhere like `packaging/debian` then it would not directly interfere with Debian packaging. But having a folder `debian` in the root would just break the Debian workflow.

For RPM based distributions a `thinkpad-scripts.spec` anywhere does not really hurt as the sources and the packager's SPEC file are usually separated into `SPECS/thinkpad-script.spec` and `SOURCES/thinkpad-scripts-XXX.tar.gz`.

# system directory

I see that you created a `system` directory for the auxiliary files. That is probably nice to organize them. Why do you install them into the Python module as well? The `install` target in the `Makefile` already installs them onto the system.

# Service

Is there a reason you start the service with `/usr/sbin/service` and not with `systemctl`? Is the former something that works across systemd, SysV and Upstart or something?

# Tablet normal

Why is the tablet normal now gone? It was added for a person who likes to have the laptop with turned screen but with normal display orientation. I found that I occasionally use that as well. As you said that the HDAPS will not be able to trigger a 180 degree rotation there would be something missing.

# ACPI module

In the `acpi.py` module you create a single class called `Acpi` with only static methods. This looks like Java to me. Essentially the class acts as a namespace. You already have a namespace `acpi` from the module. I think just removing the extra level of indentation is just fine, there is no need to the extra class.

Almost the same with the `hdaps.py`, it looks like a god-object. There are a couple of non-static member functions. I think it would be better to move all the static methods into the module scope and reduce the length of the class.

You even do `from tps.acpi import Acpi` in `tps/rotate.py` which tells me for sure that you got one superfluous namespace there.

# deamon module

You import a `deamon` and a `pidfile` module. Are they part of the standard Python library? If so, please group them to the standard library imports.

# PID file

Perhaps I am too sensitive, but I do not like PID files. Are they cleaned up properly? What happens when some program dies? What happens if the file is already there?

# Configuration option

One could debate whether a `[hdaps]` section would make sense as you have all those configuration options starting with `hdaps_` in the `[rotation]` section.

**Comment by sniffer** [comment]
Thanks for the CR I guess :) I was in a hurry to implement this so some things might have slipped and there was a lot to go around in a short time. Please find my answers below.

1). Debian packaging - I've moved it to packaging directory as you suggested. Honestly it didn't cross my mind whether this would affect debian package maintainers so its good you caught it.

2). Service - yupp, that was the idea. I've put the static files into the package_data because theoretically you could distribute this package through pypy, but I don't think it works anyway if the static files are not in a python module so we may remove it.

3). Service - service should control both systemd and sysv legacy services as it falls back to systemd on systemd enabled systems. We may stick with it. However now I've even disabled the installation of acpi hooks related to tablet mode change as the daemon reads this information anyway internally.

4). Modules - Yes, I know, this is Python, not Java. For now I'll leave it be the way it is. I've moved some file i/o code out of both classes. In Hdaps class it now is not a such a big issue, however Acpi contains only static methods. I'll review it further if it makes sense having the class if any other features were to be implemented needing sysfs/acpi interaction.

5) Daemon - There is a PEP spec this module is based on and there is talk it might get unstreamed into base Python, but for now its not.

6) Pidfiles - With systemd the pid file is obsolete, however sysv requires it. I'll prepare the code necessary to launch the service under sysv so then it will become handy. The lockfile is supposed to remove the file and if it doesn't systemd does that automatically.

7) Configuration - this makes sense. I've moved those options into a separate section.

Also, If you have a look into my repo I've pushed some more changes I was able to make today - mainly clean-up regarding entry points and converting them into a single entry point. I thought this is the way the package should work as all the multi-purpose cmdline tools behave this way nowadays (see git for example).

**Comment by martin-ueding** [comment]
You did not say anything about the `tablet_normal`. Why did you remove that?

All your changes are in a single branch, that makes it rather difficult to only merge parts of it. I guess you want all your changes to be applied at once?

What is with the `daemon` module? Is it part of Python or not? I read it like it is not part of Python and needs to be included either in here or as a dependency, right?

Do the distinct entry points still work? I for instance have a couple of scripts calling `thinkpad-dock` and `thinkpad-rotate` explictly. I would not like to break them without a major version increase. The use of sub-parsers is nice, I have not seen those before. But if definitely makes sense and makes the whole thing more discoverable. Also common options can be handled much more easily. I like that!

I will have to review all the other major changes that you made. Perhaps I will not find proper time to do so before mid February when my exams are taken care of. Before that I do not want to delve into this.

**Comment by sniffer** [comment]
``tablet_normal`` - sorry, it skipped my attention. What I did is removed the ``physically_closed`` attribute on Direction. After that the definitions of ``normal`` and ``tablet-normal`` were identical so it made sense to me to remove that (I did not see the relation to the ``physically_closed`` attribute until you've asked.).

Since then I've restored this option (as a backwards compatibility) and added the ability to disable/enable inputs when changing the ortientation: ``thinkpad rotate normal off`` should be a synonym of ``thinkpad rotate tablet-normal`` now.

``daemon`` - it's not part of Python as of now. I've added it as a deb dependency already. It's available as a deb package, at least on Willy.

distinct entry points - of course they work. I've written a layer to manipulate argv to translate the old style command syntax to the single entry point. So it is a drop in replacement, and the subcommands still work and may be removed later on if ever.

Take your time with the review and merge what you deem is worthy (hope most of them are). I'm preparing some more changes and it will take me some time to implement those anyway so its even better you hold off for now.

**Comment by jturner314** [comment]
Hi all,

I took a quick look at @sniffer's repository. Here are a few comments:

1. It would be better to install `/etc/modules-load.d/thinkpad-scripts.conf` in the `full-install` makefile rule instead of the `common-install` rule. At least on Arch Linux, I wouldn't expect installing a package (i.e. running `make install`) to automatically enable any kernel modules.
2. @sniffer have you tried using `inotify` to monitor changes in `/sys/devices/platform/hdaps/position`? If that works, we could avoid using a daemon. I would strongly prefer avoiding a daemon if possible.
3. It looks like the daemon library @sniffer is using is based on [PEP 3143](https://www.python.org/dev/peps/pep-3143/), which is currently deferred. There is an Arch Linux package for this called `python-daemon`. If we need a daemon (with support for non-systemd systems), this seems like a reasonable approach.
4. In the makefile `full-install` rule, it would be nice to also use `modprobe` to enable the necessary kernel modules and use `systemctl` to start the daemon so that the user wouldn't have to reboot.
5. If we switch to a single entry point, I'd prefer for it to be named something other than `thinkpad` -- maybe `thinkpad-scripts`? While the name `thinkpad` is not currently used by any other programs (of which I am aware), it seems a little too generic for this project.
6. As @sniffer suggested, `system/*` should be removed from the `package_data` dictionary in `setup.py`.
7. The docs need to be updated for the new config options and functionality.

I haven't looked at changes to the Python code in detail, but I like the idea.

**Comment by sniffer** [comment]
Hello guys,

It's been some time and what I had so far is playing out nicely for me. I've pushed all the changes to the develop branch, updated changelog, bumped version and pulled latest changes from upstream. Still tests and documentation needs to be updated.

I've added some additional features as cmdline options, see the changelog/git log for more information.

@jturner314 : 

1. Partly done. If I move the ''modules-load/modprobe'' files to full install, then when I build with debian ''fakeroot'' those files do not end up in the resulting ''deb'' file. So for now I've left them in the ''common-install'' rule.
2. Nope, I've not. For now I'd like to stick with this solution. This can be changed later if any issues arise.
3. Yupp. This is the only widely used solution in Python. There is no real alternative.
4. Done. However I had trouble to automatically enable/start a user based service. It has to be user based because it needs the X Auth-Info.
5. Well I know that this is an arguable move. I've added some more subcommands which make this more agreable on now. I'm leaving it for now. This can easily be changed later on (until released).
6. Removed.
7. Yes, docs and moreover tests. I'll try to follow up on the tests, since these will not allow to build the project.

If you have the time you can review it again and let me know any suggestions/errors/mistakes.

**Comment by martin-ueding** [comment]
That is quite a changeset to review! :smile:

I do a `git diff -M develop..sniffer/develop` and comment on the things that I see there.

## One huge branch

All the additional features are just in one branch. So for me it is a “everything or nothing” thing. Having a few feature branches would make this much easier to manage.

The diff that I have to go through is very long:

    76 files changed, 5138 insertions(+), 997 deletions(-)

Perhaps I am just not used to doing those large changes. It just does not feel quite right to have such a large change in one changeset.

From what I grasp, you are doing the following in your branch:

1. I18n
- Multiple entry points with `subparsers`
- Add HDAPS daemon with systemd and SysV support
- Abstract away `xrandr` and `xinput` calls in a hierarchy of abstract classes
- Add packaging information for Debian
- Add the `acpi_call` kernel module such that one can set the battery charging levels
- Change existing `tps.check_call()` invocations to `from tps import check_call` and `check_call()`
- Add a layer of abstraction (`__meta__.py`) to the `setup.py`
- Add compatibility with `distribute` in case a less modern version of `setuptools` is installed
- Add control over fan, led, and beep (the annoying system beep that I disabled in the UEFI setup?)

I would have to do a `git merge sniffer/develop --no-commit` and then manually go through all the lines with `git gui` to filter out what I do not want to take over. And that would not even work since your changes are interleaved and I could not just rip out some part of it.

Either way this is going to be painful. What is the best way to go about this? How can we sensibly break this up into smaller tasks? Right now it feels like a whole sprint in one go which is too much for me to review properly.

## Desktop file name

In `system/desktop/thinkpad-touchscreen.desktop` you have this line here:
 
```ini
Name[pl_PL]=thinkpad-touchscreen.desktop
```

That does not make sense to me. Why should the display name of this thing be just the filename in Polish?

## ACPI kernel modules

In the modules to load, I found `acpi_call` and `thinkpad_acpi`. I have used those modules before to set the battery loading levels for my ThinkPad. They are not packaged in Fedora. I have tried to do this via akmod, but that seems to be quite a pain.

## setup / meta

What is the point of creating this additional `__meta__.py` module? Isn't it easier to just put all that information into `setup.py`? Or is that needed to support ancient versions of `setuptools` before the `distribute` fork?

## Hook calling

```diff
-action=/usr/bin/thinkpad-rotate-hook %e
+action=/usr/bin/thinkpad --via-hook %e rotate
```

## SysV

Do we actually target anything which does not have systemd? If not, we don't really need all that PID-file cruft in our architecture.

## reStructuredText

The docstrings in `tps/acpi/acpicall.py` do not seem to reStructuredText, I doubt that Sphinx will parse that correctly.

## Trailing spaces

There are lots of trailing spaces in the files. They are shown in red in `git diff`, at least for me.

## PEP 8

Although there are good reasons to look [beyond PEP8](https://www.youtube.com/watch?v=wf-BqAjZb8M), I would like to keep that in my project. There seem to be `camelCased` function names. I'd prefer them to be `snail_cased`. The suggestion in PEP8 to keep two empty lines between top-level things (`class`, `def`, `import`) in a module makes it easier to read, I think.

## from ... import ...

I am not sure whether I like the `from ... import ...` style. Perhaps I am doing it just too verbose by never doing this. In C++ I try to do without the `using namespace std;` and write `std::cout` and the like. Technically all your functions have unique names, so this should not pose a problem.

## Internationalization

I18n is a noble thing to do. Although `gettext` commonly uses the underscore as the translation function, this breaks the Python debugger. If we ever want to use that, we would have a problem. So I would suggest to just use `gettext()` instead of using `_()`.

## hdaps.invert

Why is `hdaps.invert` just `-1` by default and not something like `false`?

## copyright notice

I just saw that `tps/utils.py` contains some of my functions but not my copyright header. You created this file from new, but I know that those functions are not yours because they are in `snail_case`. If we want to keep up with the per-file-licensing, we will have to maintain it.
