### ISSUE TITLE
hooks.py cannot get graphical user

### ISSUE THREAD

**Issue by jspidle** [martin-ueding/thinkpad-scripts#136]
Device is an X230Tablet, model 3435-22U running stock Ubuntu
Linux jeff-gnome16 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

When the screen is rotated, hooks.py logs: tps.hooks WARNING Unable to get graphical user. Ignoring trigger.

**Comment by jturner314** [comment]
Will you please provide the following additional information?

1. Version of `thinkpad-scripts`.
2. Version of Ubuntu.
3. Desktop environment and window manager. (It looks like GNOME with Mutter?)
4. Output of `who -u`.

Regarding 4, it would be helpful to know the output of `who -u` just from a normal terminal emulator, but ideally we'd know the output of `who -u` as seen by the ACPI hook. To achieve this, you could do the following:

1. Create a file `/usr/local/bin/get-who-u` with the contents:
   ```bash
   #!/bin/bash
   echo '=====' > /tmp/slfjk
   who -u >> /tmp/slfjk 
   echo '-----' >> /tmp/slfjk
   ```
2. Make it executable:
   ```bash
   sudo chmod +x /usr/local/bin/get-who-u
   ```
3. Create two ACPI hooks, one at `/etc/acpi/events/test-1` with the following contents:
   ```
   event=ibm/hotkey HKEY 00000080 0000500[9a]
   action=/usr/local/bin/get-who-u
   ```
   and the other at `/etc/acpi/events/test-2` with the following contents:
   ```
   event=video/tabletmode TBLT 0000008A 0000000[01].*
   action=/usr/local/bin/get-who-u
   ```
4. Restart `acpid`:
   ```bash
   sudo systemctl restart acpid
   ```
5. Rotate the screen so that one of the ACPI hooks gets called.
6. Post here the contents of `/tmp/lasjfdk` between the `=====` line and the `-----` line.
7. To clean up, delete `/usr/local/bin/get-who-u`, `/etc/acpi/events/test-1`, `/etc/acpi/events/test-2`, and `/tmp/lasjfdk`, and restart `acpid`.

**Comment by jspidle** [comment]
1. thinkpad-scripts = 4.9.0-0ubuntu2
2. 16.04 LTS
3. Gnome with cairo-dock
4. who -u from a terminal
jeff     tty2         2017-03-14 12:02 23:25        1946 (:1)
jeff     pts/0        2017-03-15 11:27   .         22935 (:1)
who -u from your script
cat /tmp/slfjk
=====
jeff     tty2         2017-03-14 12:02 23:47        1946 (:1)
jeff     pts/0        2017-03-15 11:27 00:05       22935 (:1)
output in /var/log/syslog
Mar 15 11:49:29 jeff-gnome16 thinkpad-scripts: tps.hooks WARNING Unable to get graphical user. Ignoring trigger.
Mar 15 11:49:32 jeff-gnome16 thinkpad-scripts: tps.hooks WARNING Unable to get graphical user. Ignoring trigger.

**Comment by martin-ueding** [comment]
Could you try again with the current `develop` version? There are Jim's changes that should fix the current issue.

**Comment by martin-ueding** [comment]
@jturner314's changes are now building for Ubuntu Xenial and Fedora 24, 25. This issue should then be resolved.
