### ISSUE TITLE
PPA wiped?

### ISSUE THREAD

**Issue by aarjaneiro** [martin-ueding/thinkpad-scripts#152]
It seems that the PPA no longer exists on launchpad. Is this project currently done for?

**Comment by martin-ueding** [comment]
I recently have deleted the PPA, that is correct. The problem is that I don't run Ubuntu myself any more and do not want to invest the time to run a virtual machine to package it. And I would need to support up to three versions if I do it right, the LTS, the current and previous non-LTS. There have been a few updates to the code recently which were not reflected in the PPA. Additionally the Ubuntu versions that the packages were made for are outdated and so Python versions do not quite match and so on.

I think that it is easier to just install the project from source and have the latest version than to take the PPA and get an outdated version. Anyone can of course take the code and make an Ubuntu package from it, perhaps somebody would even include it into the official Debian repositories.

**Comment by aarjaneiro** [comment]
That is understandable, thanks for letting me know!
